ci:
  skip: [pip-compile]

repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==23.1.14]
# https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/
- repo: local
  hooks:
  - id: jupyter-nb-clear-output
    name: jupyter-nb-clear-output
    files: \.ipynb$
    stages: [commit]
    language: system
    entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace